import datetime
import os

def generate_date_file():
    # 現在の日付を取得
    today = datetime.datetime.now()
    date_str = today.strftime('%Y-%m-%d')

    # ファイル名の作成
    filename = f'report_{date_str}.txt'

    # ファイルの内容を作成
    content = f'''# Weekly Report - {date_str}

This file was automatically generated by GitHub Actions.

## Summary
- Generated on: {today.strftime('%Y-%m-%d %H:%M:%S')}
- Week number: {today.strftime('%U')}
- Month: {today.strftime('%B')}

## Todo
- [ ] Review this week's goals
- [ ] Update project status
- [ ] Plan for next week
'''

    # ファイルディレクトリを作成 (必要に応じて)
    os.makedirs('reports', exist_ok=True)

    # ファイルを作成
    file_path = os.path.join('reports', filename)
    with open(file_path, 'w') as f:
        f.write(content)

    print(f'Created file: {file_path}')

if __name__ == "__main__":
    generate_date_file()
